server:
  port: 8080
spring:
  application:
    name:productosService
#main:
#  allow-bean-definition-overriding: true
data:
  mongodb:
    database: productoservice_db
    port: 27017
    host: mongo_DBc
