server:
  port: 8080
spring:
  application:
    name:tutorialsService
#main:
#  allow-bean-definition-overriding: true
data:
  mongodb:
    database: tutorialsservice_db
    port: 27017
    host: mongo_DBc
